replicaCount: 2

deploymentLabels:
  app: bookserver
  run: app

containerLabels:
  app: bookserver
  run: app

matchLabels:
  app: bookserver
  run: app

containerSpec:
  name: BookServer
  image: skaliarman/api-server
  port: 8081

service:
  type: NodePort
  port: 3200
  nodePort: 30018
  protocol: TCP
