apiVersion: v1
kind: Secret
  {{- with .Values.secrets }}
metadata:
  name: {{ .name }}
  labels:
    type: env-secret
data:
  ADMIN_USERNAME: {{ .data.adminPassword | b64enc }}
  ADMIN_PASSWORD: {{ .data.adminPassword | b64enc }}
  {{- end }}